smart_borders on
gaps inner 3
gaps outer 0
default_border pixel 3
#include catppuccin-mocha
# class                 border  bground text    indicator child_border
client.unfocused        #6272A4 #6272A4 #F8F8F2 #6272A4   #6272A4
client.focused_inactive #44475A #44475A #F8F8F2 #44475A   #44475A
client.focused          #9962b7 #9962b7 #f1f1f1 #e6da00
client.urgent           #44475A #FF5555 #F8F8F2 #FF5555   #FF5555
client.placeholder      #282A36 #282A36 #F8F8F2 #282A36   #282A36
client.background       #F8F8F2

for_window [title="微信"] floating enable
for_window [title="腾讯会议"] floating enable
for_window [title="预览"] floating enable
for_window [title="wemeetapp"] floating enable
for_window [title="Telegram"] floating enable
for_window [title="Thunar"] floating enable
for_window [title="calibre*"] floating enable

# GTK
exec {
    gsettings set org.gnome.desktop.interface icon-theme 'elementary-kde'
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
}

# set cursors theme
seat * xcursor_theme phinger-cursors-light 36

# bindsym
bindsym $mod+t exec "~/.config/sway/scripts/toggle-thunar.sh"
bindsym $mod+g exec "/usr/bin/google-chrome --enable-features=TouchpadOverscrollHistoryNavigation,WaylandWindowDecorations --enable-wayland-ime --ozone-platform=wayland --wayland-per-window-scaling --wayland-text-input-version=3"

bindsym $mod+o exec "/usr/bin/swaylock"
